package xyz.rk.bookshare.model;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.position
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.catalogid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Integer catalogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.userid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.realprice
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Double realprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.createtime
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.sold
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Byte sold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.content
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.position
     *
     * @return the value of book.position
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.position
     *
     * @param position the value for book.position
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.catalogid
     *
     * @return the value of book.catalogid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Integer getCatalogid() {
        return catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.catalogid
     *
     * @param catalogid the value for book.catalogid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setCatalogid(Integer catalogid) {
        this.catalogid = catalogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.userid
     *
     * @return the value of book.userid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.userid
     *
     * @param userid the value for book.userid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.realprice
     *
     * @return the value of book.realprice
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Double getRealprice() {
        return realprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.realprice
     *
     * @param realprice the value for book.realprice
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setRealprice(Double realprice) {
        this.realprice = realprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.createtime
     *
     * @return the value of book.createtime
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.createtime
     *
     * @param createtime the value for book.createtime
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.sold
     *
     * @return the value of book.sold
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Byte getSold() {
        return sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.sold
     *
     * @param sold the value for book.sold
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setSold(Byte sold) {
        this.sold = sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.content
     *
     * @return the value of book.content
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.content
     *
     * @param content the value for book.content
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}