package xyz.rk.bookshare.model;

import java.util.Date;

public class FailedOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failedorder.id
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failedorder.bookid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Integer bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failedorder.userid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column failedorder.createtime
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column failedorder.id
     *
     * @return the value of failedorder.id
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column failedorder.id
     *
     * @param id the value for failedorder.id
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column failedorder.bookid
     *
     * @return the value of failedorder.bookid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column failedorder.bookid
     *
     * @param bookid the value for failedorder.bookid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column failedorder.userid
     *
     * @return the value of failedorder.userid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column failedorder.userid
     *
     * @param userid the value for failedorder.userid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column failedorder.createtime
     *
     * @return the value of failedorder.createtime
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column failedorder.createtime
     *
     * @param createtime the value for failedorder.createtime
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}