package xyz.rk.bookshare.model;

import java.util.Date;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.id
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.userid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.commentid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Integer commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.content
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.createtime
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.id
     *
     * @return the value of reply.id
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.id
     *
     * @param id the value for reply.id
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.userid
     *
     * @return the value of reply.userid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.userid
     *
     * @param userid the value for reply.userid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.commentid
     *
     * @return the value of reply.commentid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.commentid
     *
     * @param commentid the value for reply.commentid
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.content
     *
     * @return the value of reply.content
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.content
     *
     * @param content the value for reply.content
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.createtime
     *
     * @return the value of reply.createtime
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.createtime
     *
     * @param createtime the value for reply.createtime
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}