package xyz.rk.bookshare.model;

import java.util.Date;

public class Token {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.id
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.userid
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.createtime
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.frame
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    private Integer frame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.freshtime
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    private Date freshtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.id
     *
     * @return the value of token.id
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.id
     *
     * @param id the value for token.id
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.userid
     *
     * @return the value of token.userid
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.userid
     *
     * @param userid the value for token.userid
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token
     *
     * @return the value of token.token
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token
     *
     * @param token the value for token.token
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.createtime
     *
     * @return the value of token.createtime
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.createtime
     *
     * @param createtime the value for token.createtime
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.frame
     *
     * @return the value of token.frame
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public Integer getFrame() {
        return frame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.frame
     *
     * @param frame the value for token.frame
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public void setFrame(Integer frame) {
        this.frame = frame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.freshtime
     *
     * @return the value of token.freshtime
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public Date getFreshtime() {
        return freshtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.freshtime
     *
     * @param freshtime the value for token.freshtime
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    public void setFreshtime(Date freshtime) {
        this.freshtime = freshtime;
    }

    @Override
    public String toString() {
        return "Token{" +
                "id=" + id +
                ", userid=" + userid +
                ", token='" + token + '\'' +
                ", createtime=" + createtime +
                ", frame=" + frame +
                ", freshtime=" + freshtime +
                '}';
    }
}