package xyz.rk.bookshare.dao;

import java.util.List;
import xyz.rk.bookshare.model.Catalog;

public interface CatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int insert(Catalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    Catalog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    List<Catalog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int updateByPrimaryKey(Catalog record);
}