package xyz.rk.bookshare.dao;

import java.util.List;
import xyz.rk.bookshare.model.FailedOrder;

public interface FailedOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failedorder
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failedorder
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int insert(FailedOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failedorder
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    FailedOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failedorder
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    List<FailedOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table failedorder
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int updateByPrimaryKey(FailedOrder record);
}