package xyz.rk.bookshare.dao;

import java.util.List;
import xyz.rk.bookshare.model.Reply;

public interface ReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int insert(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    Reply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    List<Reply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int updateByPrimaryKey(Reply record);

    List<Reply> selectByCommentId(int commentId);
}