package xyz.rk.bookshare.dao;

import java.util.List;
import xyz.rk.bookshare.model.SuccessOrder;

public interface SuccessOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successorder
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successorder
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int insert(SuccessOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successorder
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    SuccessOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successorder
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    List<SuccessOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table successorder
     *
     * @mbg.generated Mon Mar 25 13:14:37 CST 2019
     */
    int updateByPrimaryKey(SuccessOrder record);
}