package xyz.rk.bookshare.dao;

import java.util.List;
import xyz.rk.bookshare.model.Token;

public interface TokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    int insert(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    Token selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    List<Token> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated Tue Mar 26 16:50:16 CST 2019
     */
    int updateByPrimaryKey(Token record);

    Token selectByUserId(int userid);
}